// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class Address
{
    public int AddressId { get; set; }

    public Guid UserId { get; set; }

    public bool Residence { get; set; }

    public string Company { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string Province { get; set; }

    public string PostalCode { get; set; }

    public string CountryCode { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public virtual User User { get; set; }
}