// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class Article
{
    public int ContentId { get; set; }

    public string Body { get; set; }

    public int? BodyWordCount { get; set; }

    public string Takeaway { get; set; }

    public string Outline { get; set; }

    public bool? OutlineApproved { get; set; }

    public Guid UserUserId { get; set; }

    public virtual Content Content { get; set; }

    public virtual User UserUser { get; set; }
}