// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class ContentRevisionDetail
{
    public int TermRevisionId { get; set; }

    public string FieldName { get; set; }

    public string Type { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public virtual ContentRevision TermRevision { get; set; }
}