// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class ContentRelatedLink
{
    public int ContentRelatedLinkId { get; set; }

    public int ContentId { get; set; }

    public int LinkId { get; set; }

    public int Order { get; set; }

    public virtual Content Content { get; set; }

    public virtual Link Link { get; set; }
}