// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class ContentRevisionFeedback
{
    public int TermRevisionId { get; set; }

    public int? PoorGrammar { get; set; }

    public int? RepeatsInformation { get; set; }

    public int? TermNotDefined { get; set; }

    public int? NotEnoughExamples { get; set; }

    public int? RelevanceNotExplained { get; set; }

    public int? UseOfTermNotExplained { get; set; }

    public virtual ContentRevision TermRevision { get; set; }
}