// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class ContentTitleTriGram
{
    public int ContentId { get; set; }

    public int NgramId { get; set; }

    public string Ngram { get; set; }
}