// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class ContentRelatedTerm
{
    public int ContentRelatedTermId { get; set; }

    public int ContentId { get; set; }

    public int TermId { get; set; }

    public int Order { get; set; }

    public virtual Content Content { get; set; }

    public virtual Term Term { get; set; }
}