// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class ContentStatus
{
    public int ContentStatusId { get; set; }

    public string Name { get; set; }

    public int Order { get; set; }

    public virtual ICollection<ContentRevision> ContentRevisions { get; set; } = new List<ContentRevision>();

    public virtual ICollection<Content> Contents { get; set; } = new List<Content>();

    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();
}