// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class CountryCode
{
    public int Id { get; set; }

    public string CountryCode1 { get; set; }

    public string CountryName { get; set; }
}