// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class GeoData
{
    public int GeoId { get; set; }

    public string CountryCode { get; set; }

    public string RegionCode { get; set; }

    public string City { get; set; }

    public string PostalCode { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public int MetroCode { get; set; }

    public int AreaCode { get; set; }

    public string Isp { get; set; }

    public string Organization { get; set; }
}