// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class HelpPage
{
    public int HelpContentId { get; set; }

    public string Title { get; set; }

    public string Url { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? StatusChangeDate { get; set; }

    public Guid? EditedBy { get; set; }

    public string Content { get; set; }

    public bool? NodeOnly { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User EditedByNavigation { get; set; }

    public virtual HelpHierarchy HelpContent { get; set; }
}