// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class ImageMeta
{
    public long ImageId { get; set; }

    public short ImageType { get; set; }

    public string FileName { get; set; }

    public string Subfolder { get; set; }

    public string RelativeUrl { get; set; }

    public DateTime UploadDate { get; set; }

    public string UploadedBy { get; set; }

    public string AltText { get; set; }

    public string Source { get; set; }

    public string Byline { get; set; }

    public bool NeedsWatermark { get; set; }

    public virtual ICollection<Content> Contents { get; set; } = new List<Content>();

    public virtual ICollection<Tag> TagsTags { get; set; } = new List<Tag>();
}