// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class Link
{
    public int LinkId { get; set; }

    public string LinkUrl { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int LinkTypeId { get; set; }

    public int? ContentId { get; set; }

    public virtual Content Content { get; set; }

    public virtual ICollection<ContentRelatedLink> ContentRelatedLinks { get; set; } = new List<ContentRelatedLink>();
}