// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class Log
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public string Thread { get; set; }

    public string Level { get; set; }

    public string Logger { get; set; }

    public string Message { get; set; }

    public string Exception { get; set; }

    public string UserAgent { get; set; }

    public string Ipaddr { get; set; }

    public string Url { get; set; }

    public string Referrer { get; set; }

    public string User { get; set; }

    public string ServerName { get; set; }

    public string SessionTable { get; set; }
}