// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class MetroCode
{
    public int Id { get; set; }

    public string RegionCode { get; set; }

    public int MetroCode1 { get; set; }

    public string MetroName { get; set; }
}