// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class Permission
{
    public Guid RoleId { get; set; }

    public int ContentTypeId { get; set; }

    public bool Create { get; set; }

    public bool View { get; set; }

    public bool Edit { get; set; }

    public bool Delete { get; set; }

    public int ContentStatusId { get; set; }

    public virtual ContentStatus ContentStatus { get; set; }

    public virtual ContentType ContentType { get; set; }

    public virtual Role Role { get; set; }
}