// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class PlagiarismDetail
{
    public long PlagiarismMatchId { get; set; }

    public int PlagiarismId { get; set; }

    public string SourceUrl { get; set; }

    public string SourceTitle { get; set; }

    public int WordsMatching { get; set; }

    public decimal PercentageMatch { get; set; }

    public bool IsEstimate { get; set; }

    public string TextSnippet { get; set; }

    public string HtmlSnippet { get; set; }

    public virtual Plagiarism Plagiarism { get; set; }
}