// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class ProfileOption
{
    public Guid OptionId { get; set; }

    public string PropertyCategory { get; set; }

    public string PropertyNames { get; set; }

    public bool? PropertyValuesBoolean { get; set; }

    public string PropertyValuesString { get; set; }

    public bool IsActive { get; set; }
}