// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class Quote
{
    public int ContentId { get; set; }

    public string Quote1 { get; set; }

    public string Source { get; set; }

    public string Origin { get; set; }

    public string Importance { get; set; }

    public virtual Content Content { get; set; }
}