// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class RegionCode
{
    public int Id { get; set; }

    public string CountryCode { get; set; }

    public string RegionCode1 { get; set; }

    public string RegionName { get; set; }
}