// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class Role
{
    public Guid RoleId { get; set; }

    public string Description { get; set; }

    public string Name { get; set; }

    public Guid ApplicationApplicationId { get; set; }

    public virtual Application ApplicationApplication { get; set; }

    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();

    public virtual ICollection<User> UsersUsers { get; set; } = new List<User>();
}