// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class SearchTypeLog
{
    public int SearchLogId { get; set; }

    public int ContentTypeId { get; set; }

    public bool NoResults { get; set; }

    public virtual ContentType ContentType { get; set; }

    public virtual SearchLog SearchLog { get; set; }
}