// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class SearchLog
{
    public int SearchLogId { get; set; }

    public string Query { get; set; }

    public string Referer { get; set; }

    public Guid? CreatedById { get; set; }

    public DateTime AddedDate { get; set; }

    public virtual ICollection<SearchTypeLog> SearchTypeLogs { get; set; } = new List<SearchTypeLog>();
}