// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class StyleGuide
{
    public int StyleId { get; set; }

    public string StyleItem { get; set; }

    public int? StyleType { get; set; }

    public byte[] StyleImage { get; set; }

    public string Description { get; set; }

    public DateTime? LastEditDate { get; set; }

    public virtual ICollection<StyleError> StyleErrors { get; set; } = new List<StyleError>();
}