// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class StyleError
{
    public int StyleId { get; set; }

    public int StyleErrorId { get; set; }

    public string StyleErrorItem { get; set; }

    public DateTime? LastEditDate { get; set; }

    public virtual StyleGuide Style { get; set; }
}