// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class Tag
{
    public int TagId { get; set; }

    public string Name { get; set; }

    public bool Approved { get; set; }

    public bool IsCategoryTag { get; set; }

    public string AddedBy { get; set; }

    public string FriendlyDisplay { get; set; }

    public bool? IsPrimary { get; set; }

    public int? SecondaryTagId { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Content> Contents { get; set; } = new List<Content>();

    public virtual ICollection<TagRelatedTag> TagRelatedTagRelatedTagTags { get; set; } = new List<TagRelatedTag>();

    public virtual ICollection<TagRelatedTag> TagRelatedTagTagTags { get; set; } = new List<TagRelatedTag>();

    public virtual ICollection<TagSynonym> TagSynonyms { get; set; } = new List<TagSynonym>();

    public virtual ICollection<Content> ContentContents { get; set; } = new List<Content>();

    public virtual ICollection<ImageMeta> TImageTagAssociation1TagImages { get; set; } = new List<ImageMeta>();

    public virtual ICollection<User> UserUsers { get; set; } = new List<User>();
}