// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class TagRelatedTag
{
    public int TagRelatedTagId { get; set; }

    public int RelatedTagTagId { get; set; }

    public int TagTagId { get; set; }

    public virtual Tag RelatedTagTag { get; set; }

    public virtual Tag TagTag { get; set; }
}