// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class TagSynonym
{
    public int SynonymId { get; set; }

    public string Name { get; set; }

    public bool IsMisspelling { get; set; }

    public int TagTagId { get; set; }

    public virtual Tag TagTag { get; set; }
}