// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class TermSynonym
{
    public int TermId { get; set; }

    public string Name { get; set; }

    public bool IsMisspelling { get; set; }

    public int SynonymId { get; set; }

    public virtual Term Term { get; set; }
}