// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class Term
{
    public int ContentId { get; set; }

    public string Definition { get; set; }

    public string Explanation { get; set; }

    public string Acronym { get; set; }

    public string Context { get; set; }

    public int? DefinitionWordCount { get; set; }

    public int? ExplanationWordCount { get; set; }

    public virtual Content Content { get; set; }

    public virtual ICollection<ContentRelatedTerm> ContentRelatedTerms { get; set; } = new List<ContentRelatedTerm>();

    public virtual ICollection<TermSynonym> TermSynonyms { get; set; } = new List<TermSynonym>();
}