// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class Tutorial
{
    public int ContentId { get; set; }

    public Guid AuthorId { get; set; }

    public string PdfLink { get; set; }

    public virtual User Author { get; set; }

    public virtual Content Content { get; set; }

    public virtual ICollection<TutorialDetail> TutorialDetails { get; set; } = new List<TutorialDetail>();
}