// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class TutorialDetail
{
    public int DetailsId { get; set; }

    public int ContentId { get; set; }

    public int Order { get; set; }

    public string Title { get; set; }

    public string Htmltitle { get; set; }

    public string Sources { get; set; }

    public string Body { get; set; }

    public virtual Tutorial Content { get; set; }
}