// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public string Username { get; set; }

    public DateTime? CreationDate { get; set; }

    public string Email { get; set; }

    public int? FailedPasswordAnswerAttemptCount { get; set; }

    public DateTime? FailedPasswordAnswerAttemptWindowStart { get; set; }

    public int? FailedPasswordAttemptCount { get; set; }

    public DateTime? FailedPasswordAttemptWindowStart { get; set; }

    public bool IsAnonymous { get; set; }

    public bool IsApproved { get; set; }

    public bool IsLockedOut { get; set; }

    public bool? IsOnline { get; set; }

    public DateTime LastActivityDate { get; set; }

    public DateTime? LastLockedOutDate { get; set; }

    public DateTime? LastLoginDate { get; set; }

    public DateTime? LastModified { get; set; }

    public DateTime? LastPasswordChangedDate { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }

    public string PasswordAnswer { get; set; }

    public int PasswordFormat { get; set; }

    public string PasswordQuestion { get; set; }

    public string PasswordSalt { get; set; }

    public string Comment { get; set; }

    public bool? ForcePasswordReset { get; set; }

    public int PublicId { get; set; }

    public Guid ApplicationApplicationId { get; set; }

    public virtual Address Address { get; set; }

    public virtual Application ApplicationApplication { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();

    public virtual ICollection<Content> ContentUserAssignedToUsers { get; set; } = new List<Content>();

    public virtual ICollection<Content> ContentUserLockedByUsers { get; set; } = new List<Content>();

    public virtual ICollection<HelpPage> HelpPageCreatedByNavigations { get; set; } = new List<HelpPage>();

    public virtual ICollection<HelpPage> HelpPageEditedByNavigations { get; set; } = new List<HelpPage>();

    public virtual ICollection<Plagiarism> Plagiarisms { get; set; } = new List<Plagiarism>();

    public virtual Profile Profile { get; set; }

    public virtual ProfileSerial ProfileSerial { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual ICollection<Tutorial> Tutorials { get; set; } = new List<Tutorial>();

    public virtual ICollection<Role> RolesRoles { get; set; } = new List<Role>();

    public virtual ICollection<Tag> TagsTags { get; set; } = new List<Tag>();
}