// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS.Infrastructure.Configurations.Models;

public partial class ViewDetail
{
    public int ViewDetailsId { get; set; }

    public Guid UserId { get; set; }

    public int ContentId { get; set; }

    public DateTime? ActivityDate { get; set; }

    public string RemoteIp { get; set; }

    public string RequestMethod { get; set; }

    public int TimeTaken { get; set; }

    public string UserAgent { get; set; }

    public string Referrer { get; set; }

    public string Browser { get; set; }

    public string BrowserName { get; set; }

    public string BrowserPlatform { get; set; }

    public string BrowserVersion { get; set; }

    public int? AffiliateId { get; set; }

    public int? GeoId { get; set; }

    public virtual Content Content { get; set; }
}